name: CI
on: [push]
env:
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install Lighthouse CI
        run: npm install -g @lhci/cli@0.11.x
      - name: run Lighthouse CI ${{ secrets.LHCI_GITHUB_APP_TOKEN }} ${{ secrets.LHCI_TOKEN }}
        run: lhci autorun --failOnUploadFailure

